- src/AssemblyGenerator.Assemblies.cs
- src/AssemblyGenerator.Helpers.cs
- src/AssemblyGenerator.cs
- test/Lokad.ILPack.Tests/AssemblyGeneratorTest.cs
Issue #11 was caused when referenced runtime assemblies have `PublicKey` flag. This commit extends existing unit tests with forced metadata access to replicate this issue for all unit tests. Also, this commit improves the codebase by separating generated and referenced assembly name flag mapping to able apply different logic and eventually fix this issue.
Fixes: #11
> Fix full metadata access

- src/AssemblyGenerator.Attributes.cs
- src/AssemblyGenerator.Constructors.cs
- src/AssemblyGenerator.Fields.cs
- src/AssemblyGenerator.Helpers.cs
- src/AssemblyGenerator.Methods.cs
- src/AssemblyGenerator.Modules.cs
- src/AssemblyGenerator.Parameters.cs
- src/AssemblyGenerator.Properties.cs
- src/AssemblyGenerator.Types.cs
- src/AssemblyGenerator.cs
- src/Extensions.cs
- src/Extensions/IEnumerableExtensions.cs
- src/IL/MethodBodyStreamWriter.cs
- src/IL/MethodBodyWriter.cs
- src/IL/OpCodeExtensions.cs
- src/Metadata/AssemblyMetadata.Assemblies.cs
- src/Metadata/AssemblyMetadata.Constructors.cs
- src/Metadata/AssemblyMetadata.Fields.cs
- src/Metadata/AssemblyMetadata.Methods.cs
- src/Metadata/AssemblyMetadata.Parameters.cs
- src/Metadata/AssemblyMetadata.Properties.cs
- src/Metadata/AssemblyMetadata.Types.cs
- src/Metadata/AssemblyMetadata.cs
- src/Metadata/IAssemblyMetadata.cs
- src/Metadata/Metadata.cs
- src/Metadata/MetadataHelper.cs
- test/Lokad.ILPack.Tests/AssemblyGeneratorTest.cs
This commit fixes cyclic dependency by 2-pass algorithm. First pass sorts types by dependency and reserves metadata tokens for each entity definitions (fields, properties, constructors, methods and types). Second pass emits actual metadata. Referenced entities are progressively resolved since they don't need such dependency resolution. There are some measures to ensure reserved and actual emitted metadata tokens are same.
Also, this commit fixes user string handling. `OperandType.InlineString` requires user string metadata token which is allocated by `GetOrAddUserString` (`#US` in .NET metadata). Old implementation use strings in `#Strings` heap which is allocated by `GetOrAddString`.
To cover all changes, basic type dependency (`TestBasicInheritance`), external method referencing …
> Fix cyclic dependency and user string handling

- src/Metadata/AssemblyMetadata.cs
- test/Lokad.ILPack.Tests/AssemblyGeneratorTest.cs
This commit fixes null strings to support types with no namespace. Also, user strings and blobs are supported with null references now (provides a null metadata handle instead of throwing an exception). A unit test is provided with a anonymous type and a type with no namespace to support this commit.
See: #9, #28, #33
> Fix null strings

- src/IL/MethodBodyReader.cs
- src/Metadata/AssemblyMetadata.Constructors.cs
- test/Lokad.ILPack.Tests/AssemblyGeneratorTest.cs
In old implementation, if a type reference is found, all of its public constructor references are resolved. But, if a type reference is not referenced as a type at anywhere and one of its constructor is invoked in a method body, old implementation mistakenly assumed constructor reference should be available. This commit fixes this problem. Also, a new unit test is added to demonstrate the problem.
See: #33
> Fix inline constructor reference resolving

- src/AssemblyGenerator.Types.cs
- src/Metadata/AssemblyMetadata.Properties.cs
- src/Metadata/Metadata.cs
- test/Lokad.ILPack.Tests/AssemblyGeneratorTest.cs
Property serialization was wrong due to double metadata token reservation for getter and setter methods. This commit fixes this problem and adds a new unit test for property serialization.
See: #9
> Fix property serialization

- test/Lokad.ILPack.Tests/AssemblyGeneratorTest.cs
Property setters are supposed to be void return with implicit value parameter
> Fixed test case incorrectly generating property setters

- src/IL/MethodBodyStreamWriter.cs
- src/Metadata/AssemblyMetadata.cs
- src/Metadata/IAssemblyMetadata.cs
This is a fix to generate the (previously missing) local variable signatures that caused any method with local variables to crash with a runtime exception.
Note this probably only works for system types.  Not tested with externally referenced types.
> Fix for runtime crash for any method with local variable

- src/Metadata/AssemblyMetadata.Types.cs
For for type references to instantiated generic types.
eg: this C# code:
```
event Action<int> MyEvent;
```
was producing metadata as:
```
event Action<> MyEvent
```
> Fix for references to instantiated generic types

- src/AssemblyGenerator.Types.cs
- src/AssemblyGenerator.cs
- test/Lokad.ILPack.Tests/.gitignore
- test/Lokad.ILPack.Tests/Lokad.ILPack.Tests.csproj
- test/Lokad.ILPack.Tests/RewriteTest.cs
- test/Lokad.ILPack.Tests/dump.bat
- test/RewriteOriginal/MyClass.cs
Note: this approach requires one small (but worthwhile) change to ILPack to allow it to rename the assembly and namespace meta data that it generates.  This allows the test runner to load both the original and the cloned assembly without needing AppDomain support (which netcore doesn't have).
Overall this is a much cleaner approach than previous pull request #51 which I've retracted.  Also I've removed the original test cases from RewriteTests which weren't really effective in detecting problems and this new approach should cover everything they did anyway.
The notes below are copied from comments included in the RewriteTests.cs test case file.
Finally, note that some of the test cases included here are failing, but they're separate issues to this pull request.
---
These test cases work …
> Update to the RewriteTests test cases to actually invoke the newly rewritten assembly

- src/AssemblyGenerator.Attributes.cs
- src/AssemblyGenerator.cs
Attribute support was previously comment out.  This is a rewrite that uses the System.Reflection.Metadata.Ecma335 encoders for customer attribute data (rather than trying to manually build those blobs).  Also, added call to copy custom attributes for the assembly itself.
Seems to work well for scalar types.  Array data not supported (should throw exception)
Testing with RewriteOriginal shows compiler generated attributes, assembly info attributes getting copied across by idasm.  Unit tests for a couple of assembly attributes are included in separate PR #52
> Rewrote support for custom attributes (scalars only)

- src/IL/MethodBodyWriter.cs
This PR addresses an issue where the generated MSIL for branch targets was simply wrong.  Not sure what the old code was trying to do, but it was generating an increasing index for each branch target (instead of the actual address which was already directly available from the Instruction) while maintaining map of branch targets that were never actually used.
This PR fixes this unit test case RewriteTest.InvokeNoParamEventWithNoListeners
> Fix for generating incorrect MSIL branch targets

- src/AssemblyGenerator.Types.cs
- src/Metadata/AssemblyMetadata.Types.cs
- src/Metadata/Metadata.cs
I noticed these unused TypeDefinitionMetadata.xxxIndex properties the other day when adding support for event maps.  If these are intended for some future purpose, please disregard the PR.
> Removed unused properties

- src/Metadata/AssemblyMetadata.Methods.cs
This fixes calling of imported generic methods from other assemblies.  
eg: `T System.Threading.Interlocked.CompareExchange<T>(T&, T, T)` can now be successfully called.
This, together with other pending pull requests, fixes event firing in the rewritten `TestSubject` assembly and all unit tests (except those commented out) now pass!
> Fixed generic method signature encoding

- src/Lokad.ILPack.csproj
- src/Metadata/AssemblyMetadata.Assemblies.cs
This PR resolves issues with emitting references to forwarded types, including but not limited to forwards from System.Runtime to System.Private.Core.
It works, by reading the metadata for all referenced assemblies, extracting all the forwarded types and creating a map of the forward type to the original assembly that forwarded it.  This lets us emit type references to the forwarding assembly instead of the implementation assembly.
Unfortunately, this requires unsafe code to be enabled as we need Assembly.TryGetRawMetadata which returns a pointer.
Note that this change breaks all unit tests if not combined with PR #55 (because of special handling required for byref parameters to prevent it looking for an assembly reference that doesn't exist)
> Fix issues with types loaded through assembly type forwarding

- src/Metadata/AssemblyMetadata.Assemblies.cs
eg: System.AggregateException is forwarded by both
System.Threading.Tasks and System.Runtime
> Handle types forwarded by multiple referenced assemblies

- src/Extensions.cs
This is a small tweak to generate signatures that better match what the C# compiler produces.
SZArrays are essentially a short cut for a one-dimensional, zero based array shape.
No unit test for this because runtime result doesn't change. Can be confirmed in ildasm listing by checking single dimension arrays appearing as `[]` instead of `[...]`.
> Use SZArray instead of shaped arrays for single rank arrays.

- src/AssemblyGenerator.Properties.cs
No unit tests for this because .NET doesn't actually require this flag on the prop def (it figures it out from the accessor methods), but this is more correct.
See also, the "note" in EMCA 335 under "Property : 0x17", top of pp242
> Fix to tag PropDefs with instance flag

- Lokad.ILPack.sln
- src/Properties/InternalsVisibleTo.cs
- test/Sandbox/.gitignore
- test/Sandbox/Program.cs
- test/Sandbox/Sandbox.csproj
- test/Sandbox/asm.bat
- test/Sandbox/dump.bat
- test/SandboxSubject/MyClass.cs
- test/SandboxSubject/SandboxSubject.csproj
Explanation comment from Sandbox/Program.cs copied below...
---
This is intended as a place to work on problem areas that currently aren't even
stable enough to write unit tests for yet.
In particular if something in the TestSubject project causes ILPack to throw an
exception, all the unit tests will fail since the re-written assembly isn't produced.
The idea is to work on these kinds of problems here and once working, move the test
code into the unit tests.
Other advantages to Sandbox over unit tests:
- SandboxSubject can be kept very small and targeted to a particular problem allowing 
for easier inspection of ildasm/mddumper analysis
- Quick F5 debug/fix/re-run cycle (instead of having to select a specific unit test to run)
Sandbox works almost identically to the RewriteTest cases - it …
> Added Sandbox project

- src/AssemblyGenerator.Attributes.cs
- src/AssemblyGenerator.Events.cs
- src/AssemblyGenerator.Properties.cs
- test/Lokad.ILPack.Tests/RewriteTest.Attributes.cs
- test/Lokad.ILPack.Tests/RewriteTest.Nullable.cs
- test/Lokad.ILPack.Tests/RewriteTest._boot.cs
- test/TestSubject/MyAttribute.cs
- test/TestSubject/MyClass.Attributes.cs
- test/TestSubject/MyClass.Nullable.cs
- Added support for attribute arrays (both placed and named), with unit tests
- Added support for custom attributes
- Fix for incorrectly emitting base fields and events (required for previous to work)
- Unit test for Nullable types (held back unit test for PR#82)
> Fix attribute arrays, fix incorrectly emitting base fields and events, tests

- src/IL/MethodBodyWriter.cs
- test/Lokad.ILPack.Tests/RewriteTest.Methods.cs
- test/TestSubject/MyClass.Methods.cs
Fixes method parameter position encoding for methods with more than 4 parameters (including `this` for instance methods). Includes relevant unit tests.
Resolves: #84
> Fix method parameter position encoding

- src/Extensions.cs
- src/Lokad.ILPack.csproj
- src/Metadata/AssemblyMetadata.Methods.cs
- src/Metadata/AssemblyMetadata.Types.cs
- test/Lokad.ILPack.Tests/Lokad.ILPack.Tests.csproj
- test/Lokad.ILPack.Tests/RewriteTest._boot.cs
- test/TestSubject/TestSubject.csproj
I am implementing ways to have this package on .NET Standard & .NET Framework.
I have been able to gather all Metadata and tests partially pass. I would like to discuss a little how to fix the problem I am having with reserved and actual handles. They are not the same on .NET 4.6.
I am trying to use this package on https://github.com/arlm/Sigil-vNext to implement saving the generated Dynamic Assemblies but that does not work for .NET Standard for now and I have not been able to install Lokad.ILPack on any of the targets (The NuGet version targets .NET Core only).
> .NET Standard 2.0 & .NET 4.6 Support 

- src/AssemblyGenerator.Methods.cs
- src/AssemblyGenerator.Types.cs
- src/Extensions.cs
- src/Metadata/AssemblyMetadata.Types.cs
- Fixed the nested type reference issue. The scope of a nested type is its declaring type, not the assembly.
- Fixed an issue with parameter declarations of generic methods. `Extensions.FromSystemType` now uses `SignatureTypeEncoder.GenericMethodTypeParameter` or `SignatureTypeEncodes.GenericTypeParameter` depending on whether the generic type argument is declared by a method or by a type.
- The declared interfaces were reduced to those interfaces that are not already declared by the base type. This prevents the generation of dependencies not covered by the `GetReferencedAssemblies` method.
- The generation of the interface map has been moved from AssemblyGenerator.Methods.cs to AssemblyGenerator.Types.cs. This covers cases where base type methods are used to implement methods of newly …
> Fixed nested type reference issue, improved support for generic methods, improved interface map generation

- src/AssemblyGenerator.Types.cs
- test/TestSubject/MyClass.Interfaces.cs
Declared interfaces that implement interfaces currently fail when building the interface map. Instead of trying to build the map, mark the type implements the interface and then skip over handling mapping.
> Support interfaces implementing interfaces

- src/AssemblyGenerator.Attributes.cs
- src/AssemblyGenerator.Methods.cs
- src/AssemblyGenerator.Types.cs
- test/TestSubject/MyClass.Methods.cs
This was observed when attempting to serialize the `ComImport` attribute. Upon further investigation it was discovered that P/Invokes were also not supported so that has been added. Testing for the P/Invoke case is incomplete due to lack of stable binary to use. It would be possible to make a pure managed solution here if the [DNNE](https://github.com/AaronRobinsonMSFT/DNNE) library was leveraged to create native exports. However, that requires .NET 5+.
> Handle some pseudo attributes during serialization.

- src/Extensions.cs
- src/Lokad.ILPack.csproj
- test/Lokad.ILPack.Tests/Lokad.ILPack.Tests.csproj
- test/Sandbox/Sandbox.csproj
- test/SandboxSubject/SandboxSubject.csproj
- test/TestSubject/TestSubject.csproj
- Kept only .NET Standard 2.0 as a target platform for the NuGet package
- Replaced .NET Core 2.1 (out of support) with .NET Core 3.1 and .NET 5
> Cleaned up old and unsupported TFMs from the project files

- src/AssemblyGenerator.Constructors.cs
- test/Lokad.ILPack.Tests/RewriteTest.Delegates.cs
- test/TestSubject/MyClass.Delegates.cs
Constructors with an empty body should provide negative value as body offset (no RVA). (Resolves #121)
> Use proper offset for empty bodies

- src/AssemblyGenerator.Types.cs
- src/AssemblyGenerator.cs
- test/Lokad.ILPack.Tests/AssemblyGeneratorTest.cs
Fixes #37. Use a simple approach for entry point definition - it works fine for .NET 3.1 and later.
This PR also contains more unit tests for the name unescaping feature and changes for existing (incorrect) tests.
> Pass proper entry point RVA into the `ManagedPEBuilder` constructor

- src/Extensions.cs
- src/IL/MethodBodyReader.cs
- src/IL/MethodBodyWriter.cs
- src/IL/SignatureInfo.cs
- src/Metadata/AssemblyMetadata.Methods.cs
- src/Metadata/AssemblyMetadata.cs
- src/Metadata/IAssemblyMetadata.cs
- test/Lokad.ILPack.Tests/Lokad.ILPack.Tests.csproj
- test/Lokad.ILPack.Tests/RewriteTest.Methods.cs
- test/TestSubject/MyClass.Methods.cs
- test/TestSubject/MyUnsafe.cs
- test/TestSubject/TestSubject.csproj
Inline signatures used by the `calli` MSIL instruction are part of a new high-performance low-level unsafe platform interop (function pointers in `delegate*` format). The current implementation handles most of the practical use cases except the single one: function pointers as arguments of function pointers. I'll open a separate issue for this use case (very rare). This PR completely covers and fixes #106.
> Correctly process inline signatures

- src/AssemblyGenerator.Modules.cs
Fixed problem that can be easily reproduced in the .NET SDK 7.0 - module can have attributes defined in the module itself.
> Module attributes should be processed after types definitions.
